Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/det_teacher_swin/
  save_epoch_step: 1200
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [3000, 2000]
  cal_metric_during_train: False
  pretrained_model: output/det_teacher_swin/best_accuracy.ptparams
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img: /data/OCR_data/txtdet/multi_det_data/multi_splits/split1/labels_eval_all.txt
  save_res_path: ./output/det_teacher_swin/res.txt
  distributed: False

Architecture:
  name: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: SwinTransformer
        in_channels: 3
        pretrain_img_size: 384
        use_checkpoint: False
        embed_dims: 128
        window_size: 12
        depths: [2, 2, 18, 2]
        num_heads: [4, 8, 16, 32]
      Neck:
        name: FPNC
        in_channels: [192, 384, 768, 1536]
        lateral_channels: 256
      Head:
        name: DBHead
        in_channels: 256
        kernel_list: [3,2,2]
        k: 50

    Student2:
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: SwinTransformer
        in_channels: 3
        pretrain_img_size: 384
        use_checkpoint: False
        embed_dims: 128
        window_size: 12
        depths: [2, 2, 18, 2]
        num_heads: [4, 8, 16, 32]
      Neck:
        name: FPNC
        in_channels: [192, 384, 768, 1536]
        lateral_channels: 256
        upsample: bilinear
      Head:
        name: DBHead
        in_channels: 256
        kernel_list: [3,2,2]
        k: 50


Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDMLLoss:
      model_name_pairs:
      - ["Student", "Student2"]
      maps_name: "thrink_maps"
      weight: 1.0
      # act: None
      model_name_pairs: ["Student", "Student2"]
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list: ["Student", "Student2"]
      # key: maps
      name: DBLoss
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 0
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DistillationDBPostProcess
  model_name: ["Student", "Student2"]
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
  visual: True

Metric:
  name: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /ldap_home/xuenong.hong/det_data/multi_det_data/
    label_file_list:
      - /ldap_home/xuenong.hong/det_data/multi_det_data/multi_splits/split1/labels_train.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - CopyPaste:
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 4
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /ldap_home/xuenong.hong/det_data/multi_det_data/
    label_file_list:
      - /ldap_home/xuenong.hong/det_data/multi_det_data/labels_eval_all.txt
    transforms:
    
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2
