Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/det_swin_base/
  save_epoch_step: 1200
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [3000, 2000]
  cal_metric_during_train: False
  pretrained_model: 
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img: test_imgs
  save_res_path: res/res.txt
  distributed: False

Architecture:
  name: RetinaFace
  min_sizes: [[8, 16], [32, 64], [128, 256]]
  predict_landmark: True
  Backbone:
    name: SwinTransformer
    in_channels: 3
    pretrain_img_size: 384
    use_checkpoint: False
    embed_dims: 128
    window_size: 12
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
  Neck:
    name: FPNC
    in_channels: [192, 384, 768, 1536]
    lateral_channels: 256
    upsample: bilinear
  Head:
    name: DBHead
    in_channels: 256
    kernel_list: [3,2,2]
    k: 50



Loss:
  name: MultiBoxLoss
  num_classes: num_classes
  overlap_thresh: 0.35
  prior_for_matching: True
  bkg_label: 0
  neg_mining: True
  neg_pos: 7
  neg_overlap: 0.35
  encode_target: False


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 0
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 2
  visual_output: False
  use_dilation: True

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    label_file_list: /home/xuenong/projects/Data/face_detection_dataset/WiderFace/train.txt
    data_dir: /home/xuenong/projects/Data/face_detection_dataset/WiderFace/WIDER_train/images
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      # - CopyPaste:
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/xuenong/projects/Data/face_detection_dataset/WiderFace/WIDER_train/images
    label_file_list: /home/xuenong/projects/Data/face_detection_dataset/WiderFace/train.txt
    transforms:
    
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2
