Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/det_mobilenetv3_swin_cml/
  save_epoch_step: 100
  eval_batch_step: [50000, 5000]
  cal_metric_during_train: false
  pretrained_model: ./output/det_mobilenetv3_swin_cml/best_accuracy.ptparams
  checkpoints: ./output/det_mobilenetv3_swin_cml/best_accuracy
  save_inference_dir: null
  use_visualdl: false
  infer_img: test_imgs
  save_res_path: res/res.txt
  distributed: False

Architecture:
  name: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      pretrained: ./pretrained_weights/mobilenet_v3_pytorch_pretrained.ptparams
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: mobilenet_v3_large
      Neck:
        name: FPNC
        lateral_channels: 256
      Head:
        name: DBHead
        in_channels: 256
        kernel_list: [3,2,2]
        k: 50
    Student2:
      pretrained: ./pretrained_weights/mobilenet_v3_pytorch_pretrained.ptparams
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: mobilenet_v3_large
      Neck:
        name: FPNC
        lateral_channels: 256
      Head:
        name: DBHead
        in_channels: 256
        kernel_list: [3,2,2]
        k: 50
    Teacher:
      pretrained: ./pretrained_weights/det_db_swin_student1_pretrained.ptparams
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: SwinTransformer
        in_channels: 3
        pretrain_img_size: 384
        use_checkpoint: False
        embed_dims: 128
        window_size: 12
        depths: [2, 2, 18, 2]
        num_heads: [4, 8, 16, 32]
      Neck:
        name: FPNC
        in_channels: [192, 384, 768, 1536]
        lateral_channels: 256
      Head:
        name: DBHead
        in_channels: 256
        kernel_list: [3,2,2]
        k: 50

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDilaDBLoss:
      weight: 1.0
      model_name_pairs:
      - ["Student", "Teacher"]
      - ["Student2", "Teacher"]
      key: maps
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
  - DistillationDMLLoss:
      model_name_pairs:
      - ["Student", "Student2"]
      maps_name: "thrink_maps"
      weight: 1.0
      model_name_pairs: ["Student", "Student2"]
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list: ["Student", "Student2"]
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.00005
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05

PostProcess:
  name: DistillationDBPostProcess
  model_name: ["Student"]
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /ldap_home/xuenong.hong/det_data/multi_det_data/
    label_file_list:
      - /ldap_home/xuenong.hong/det_data/multi_det_data/multi_splits/split1/labels_train.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - CopyPaste:
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 4
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /ldap_home/xuenong.hong/det_data/multi_det_data/
    label_file_list:
      - /ldap_home/xuenong.hong/det_data/multi_det_data/labels_eval_all.txt
    transforms:
    
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2